name: ci

on:
  push:
      branches: ["master"]

jobs:
     laravel-tests:

      runs-on:  ubuntu-latest

      steps:
       - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
